using Common.EnumStringValues;

namespace DevOps.Primitives.TypeScript
{
    public enum TsConfigLib : byte
    {
        [EnumStringValue(nameof(ES5))]
        ES5,
        [EnumStringValue(nameof(ES6))]
        ES6,
        [EnumStringValue(nameof(ES2015))]
        ES2015,
        [EnumStringValue(nameof(ES7))]
        ES7,
        [EnumStringValue(nameof(ES2016))]
        ES2016,
        [EnumStringValue(nameof(ES2017))]
        ES2017,
        [EnumStringValue(nameof(ES2018))]
        ES2018,
        [EnumStringValue(nameof(ESNext))]
        ESNext,
        [EnumStringValue(nameof(DOM))]
        DOM,
        [EnumStringValue("DOM.Iterable")]
        DOM_Iterable,
        [EnumStringValue(nameof(WebWorker))]
        WebWorker,
        [EnumStringValue(nameof(ScriptHost))]
        ScriptHost,
        [EnumStringValue("ES2015.Core")]
        ES2015_Core,
        [EnumStringValue("ES2015.Collection")]
        ES2015_Collection,
        [EnumStringValue("ES2015.Generator")]
        ES2015_Generator,
        [EnumStringValue("ES2015.Iterable")]
        ES2015_Iterable,
        [EnumStringValue("ES2015.Promise")]
        ES2015_Promise,
        [EnumStringValue("ES2015.Proxy")]
        ES2015_Proxy,
        [EnumStringValue("ES2015.Reflect")]
        ES2015_Reflect,
        [EnumStringValue("ES2015.Symbol")]
        ES2015_Symbol,
        [EnumStringValue("ES2015.Symbol.WellKnown")]
        ES2015_Symbol_WellKnown,
        [EnumStringValue("ES2016.Array.Include")]
        ES2016_Array_Include,
        [EnumStringValue("ES2017.object")]
        ES2017_object,
        [EnumStringValue("ES2017.SharedMemory")]
        ES2017_SharedMemory,
        [EnumStringValue("ES2017.TypedArray")]
        ES2017_TypedArrays,
        [EnumStringValue("ES2018.Promise")]
        ES2018_Promise,
        [EnumStringValue("ES2018.RegExp")]
        ES2018_RegExp,
        [EnumStringValue("ESNext.AsyncIterable")]
        ESNext_AsyncIterable,
        [EnumStringValue("ESNext.Array")]
        ESNext_Array
    }
}
